null=/com/wmp/speed_bump/common/background/resource/icon/%theme_type%/12-misc/circle.png
icon=/com/wmp/speed_bump/common/background/resource/icon/%theme_type%/icon.png
download=/com/wmp/speed_bump/common/background/resource/icon/%theme_type%/9-media/download.png
task=/com/wmp/speed_bump/common/background/resource/icon/%theme_type%/10-editing/clipboard.png
settings=/com/wmp/speed_bump/common/background/resource/icon/%theme_type%/8-ui/settings.png
about=/com/wmp/speed_bump/common/background/resource/icon/%theme_type%/8-ui/info-02.png
folder=/com/wmp/speed_bump/common/background/resource/icon/%theme_type%/9-media/folder.png
refresh=/com/wmp/speed_bump/common/background/resource/icon/%theme_type%/8-ui/refresh.png
save=/com/wmp/speed_bump/common/background/resource/icon/%theme_type%/8-ui/save.png
new=/com/wmp/speed_bump/common/background/resource/icon/%theme_type%/11-symbols/plus.png
file=/com/wmp/speed_bump/common/background/resource/icon/%theme_type%/9-media/paper.png
pause=/com/wmp/speed_bump/common/background/resource/icon/%theme_type%/9-media/stop.png
start=/com/wmp/speed_bump/common/background/resource/icon/%theme_type%/9-media/play.png
close=/com/wmp/speed_bump/common/background/resource/icon/%theme_type%/8-ui/cross.png
edit=/com/wmp/speed_bump/common/background/resource/icon/%theme_type%/10-editing/pencil.png
scan=/com/wmp/speed_bump/common/background/resource/icon/%theme_type%/9-media/scan.png
login=/com/wmp/speed_bump/common/background/resource/icon/%theme_type%/8-ui/user-avatar-02.png
choose=/com/wmp/speed_bump/common/background/resource/icon/%theme_type%/8-ui/grid-add.png
power_switch=/com/wmp/speed_bump/common/background/resource/icon/%theme_type%/9-media/power-switch.png
link=/com/wmp/speed_bump/common/background/resource/icon/%theme_type%/9-media/share.png
trash=/com/wmp/speed_bump/common/background/resource/icon/%theme_type%/9-media/trash.png
update=/com/wmp/speed_bump/common/background/resource/icon/%theme_type%/9-media/cloud-download.png
import = /com/wmp/speed_bump/common/background/resource/icon/%theme_type%/9-media/import.png
plugin = /com/wmp/speed_bump/common/background/resource/icon/%theme_type%/8-ui/grid-add.png
eyedropper=/com/wmp/speed_bump/common/background/resource/icon/%theme_type%/10-editing/eyedropper.png
issue = /com/wmp/speed_bump/common/background/resource/icon/%theme_type%/9-media/bug.png
license = /com/wmp/speed_bump/common/background/resource/icon/%theme_type%/9-media/protect.png

download_speed=/com/wmp/speed_bump/common/background/resource/icon/%theme_type%/9-media/download.png
download_size=/com/wmp/speed_bump/common/background/resource/icon/%theme_type%/9-media/memory-card.png
share_speed=/com/wmp/speed_bump/common/background/resource/icon/%theme_type%/9-media/export.png
share_size=/com/wmp/speed_bump/common/background/resource/icon/%theme_type%/9-media/share.png
download_success=/com/wmp/speed_bump/common/background/resource/icon/%theme_type%/8-ui/tick.png
download_failed=/com/wmp/speed_bump/common/background/resource/icon/%theme_type%/8-ui/cross.png
file_merge=/com/wmp/speed_bump/common/background/resource/icon/%theme_type%/9-media/file.png

tool-kit=/com/wmp/speed_bump/common/background/resource/icon/%theme_type%/2-items/tool-kit.png
msg-center=/com/wmp/speed_bump/common/background/resource/icon/%theme_type%/9-media/message-02.png

# 状态栏（左侧任务运行状态）
statusbar.running=/com/wmp/speed_bump/common/background/resource/icon/%theme_type%/9-media/download.png
statusbar.idle=/com/wmp/speed_bump/common/background/resource/icon/%theme_type%/10-editing/clipboard.png

info = /com/wmp/speed_bump/common/background/resource/icon/%theme_type%/8-ui/info-02.png
warn = /com/wmp/speed_bump/common/background/resource/icon/%theme_type%/8-ui/exclamation-02.png
error = /com/wmp/speed_bump/common/background/resource/icon/%theme_type%/8-ui/prohibited.png
question = /com/wmp/speed_bump/common/background/resource/icon/%theme_type%/8-ui/question-mark.png