app_name=减速带

selection_all=全选
selection_none=全不选
selection_reverse=反选

quality=质量
codecs=编码

video=视频
audio=音频
download=下载

error=错误
warn=警告
info=信息

enter=确认
cancel=取消
save=保存

learn=了解更多

save_path=保存路径
temp_path=缓存数据路径

