frame=窗口
frame.is_always_top=置顶状态
frame.refresh=刷新
frame.refresh.tooltip=只能刷新应用数据和界面UI，部分组件内已有的数据不做更新
frame.update_frame=更新界面(测试ing)
frame.update_frame.tip=更新界面需要重新加载窗口，请确保所有下载已完成
frame.exit=关闭程序
app=软件
app.disclaimer=免责声明
app.about=关于