bili_special_settings=哔哩哔哩设置
bili_special_settings.login=登录哔哩哔哩
bili_special_settings.login.scan_code=扫码登录
bili_special_settings.login.link_bilbili_url=打开登录链接
bili_special_settings.login.loggedOut=退出登录
bili_special_settings.login.QR_refresh=刷新二维码
bili_special_settings.login.scan_code_tip=请使用哔哩哔哩客户端扫码登录，二维码180秒有效期，失效请刷新
bili_special_settings.login.scanCode=扫码登录
bili_special_settings.quality=视频默认画质(制作ing)
bili_special_settings.open_link.error=打开链接失败
bili_special_settings.get_qr_code.error=获取二维码失败
bili_special_settings.login_process.error=登录过程出错
bili_special_settings.cannot_open_browser=无法打开浏览器
bili_special_settings.get_qr_code_failed=获取二维码失败
bili_special_settings.login_success_sessdata=登录成功！SESSDATA: 
bili_special_settings.login_failed_or_timeout=登录失败或超时
bili_special_settings.login_process_error=登录过程中发生错误
bili_special_settings.qr_code_generated=二维码已生成
bili_special_settings.poll_login_status_url=轮询登录状态URL:
bili_special_settings.login_success=登录成功
bili_special_settings.qr_code_expired=二维码已过期，请重新获取
bili_special_settings.scanned_confirm=已扫码，请在手机上确认...
bili_special_settings.waiting_scan=等待扫码...
bili_special_settings.unknown_status_code=未知状态码:
ffmpeg_special_settings=FFmpeg设置
ffmpeg_special_settings.setLocalPath=设置本地FFmpeg路
ffmpeg_special_settings.isUseLocal=是否使用本地FFmpeg
ffmpeg_special_settings.isUseLocal.tip=内置的文件合并会重编码速度特慢，建议使用本地的
ffmpeg_special_settings.setLocalPath.tip=设置时请选择程序(ffmpeg.exe/ffmpeg)所在的文件夹（通常在bin），而非程序
special_settings=专项设置
github_accelerate_special_settings=Github加速
github_accelerate_special_settings.start=启动Github加速
github_accelerate_special_settings.set_accelerate_station=设置加速站
github_accelerate_special_settings.set_accelerate_station.custom=自定义
ffmpeg_special_settings.is_use_hardware_acceleration=是否使用硬件加速

