video_handle=视频处理
video_handle.create_merge_task=创建合流任务
video_handle.create_merge_task.video_path=视频位置
video_handle.create_merge_task.audio_path=音频位置

video_handle.file_name_edit=文件名：

video_handle.create_merge_task.run_tip=正在合并，过程无法暂停
video_handle.create_merge_task.merge_fail=合并失败

video_handle.reset_video_info.file_selection=选择要编辑的文件：
video_handle.reset_video_info.edit_file_name=文件名：
video_handle.reset_video_info=修改视频格式和编码
video_handle.reset_video_info.tip=将不可播放的格式/编码改到更适合你的播放器
video_handle.reset_video_info.edit_video_format=视频格式：
video_handle.reset_video_info.edit_video_codecs=视频编码：
video_handle.reset_video_info.edit_audio_codecs=音频编码：
video_handle.reset_video_info.file_selection_error_title=文件路径异常
