settings=通用设置
settings.refresh.tool_tip_text=将本地数据加载到设置页
settings.refresh=刷新
settings.save=保存
settings.web=网络/下载设置
settings.web.isUseSsl=是否使用SSL
settings.personalized=个性化
settings.personalized.theme=主题设置：
settings.data_control=数据管理
settings.web.thread_num=线程数：
settings.web.location=下载位置：
settings.personalized.font=字体设置：
settings.personalized.font_size=默认字体大小：