bili_special_settings.login=登录哔哩哔哩
bili_special_settings.login.link_bilbili_url=打开登录链接
bili_special_settings.login.loggedOut=退出登录
bili_special_settings.login.QR_refresh=刷新二维码
bili_special_settings.login.scan_code_tip=请使用哔哩哔哩客户端扫码登录，二维码180秒有效期，失效请刷新
bili_special_settings.login.scanCode=扫码登录
bili_special_settings.quality=视频默认画质(制作ing)
ffmpeg_special_settings.isUseLocal=是否使用本地FFmpeg
ffmpeg_special_settings.isUseLocal.tip=内置的文件合并会重编码速度特慢，建议使用本地的
ffmpeg_special_settings.setLocalPath.tip=设置时请选择程序所在的文件夹（通常在bin），而非程序
special_settings = 专项设置