null=/icon/null.png
icon=/icon/%theme_type%/icon.png
download=/icon/%theme_type%/9-media/download.png
task=/icon/%theme_type%/10-editing/clipboard.png
settings=/icon/%theme_type%/8-ui/settings.png
about=/icon/%theme_type%/8-ui/info-02.png
folder=/icon/%theme_type%/9-media/folder.png
refresh=/icon/%theme_type%/8-ui/refresh.png
save=/icon/%theme_type%/8-ui/save.png
new=/icon/%theme_type%/11-symbols/plus.png
file=/icon/%theme_type%/9-media/paper.png
pause=/icon/%theme_type%/9-media/stop.png
start=/icon/%theme_type%/9-media/play.png
close=/icon/%theme_type%/8-ui/cross.png
edit=/icon/%theme_type%/10-editing/pencil.png
scan=/icon/%theme_type%/9-media/scan.png
login=/icon/%theme_type%/8-ui/user-avatar-02.png
choose=/icon/%theme_type%/8-ui/grid-add.png
power_switch=/icon/%theme_type%/9-media/power-switch.png
link=/icon/%theme_type%/9-media/share.png
trash=/icon/%theme_type%/9-media/trash.png
update=/icon/%theme_type%/9-media/cloud-download.png
import = /icon/%theme_type%/9-media/import.png
plugin = /icon/%theme_type%/8-ui/grid-add.png
eyedropper=/icon/%theme_type%/10-editing/eyedropper.png
issue = /icon/%theme_type%/9-media/bug.png
license = /icon/%theme_type%/9-media/protect.png

download_speed=/icon/%theme_type%/9-media/download.png
download_size=/icon/%theme_type%/9-media/memory-card.png
share_speed=/icon/%theme_type%/9-media/export.png
share_size=/icon/%theme_type%/9-media/share.png
download_success=/icon/%theme_type%/8-ui/tick.png
download_failed=/icon/%theme_type%/8-ui/cross.png
file_merge=/icon/%theme_type%/9-media/file.png

tool-kit=/icon/%theme_type%/2-items/tool-kit.png
msg-center=/icon/%theme_type%/9-media/message-02.png

info = /icon/%theme_type%/8-ui/info-02.png
warn = /icon/%theme_type%/8-ui/exclamation-02.png
error = /icon/%theme_type%/8-ui/prohibited-02.png
