null=/icon/null.png
icon=/icon/%theme_type%/icon.png
download=/icon/%theme_type%/9-media/download.png
task=/icon/%theme_type%/10-editing/clipboard.png
settings=/icon/%theme_type%/8-ui/settings.png
about=/icon/%theme_type%/8-ui/info-02.png
folder=/icon/%theme_type%/9-media/folder.png
refresh=/icon/%theme_type%/8-ui/refresh.png
save=/icon/%theme_type%/8-ui/save.png
new=/icon/%theme_type%/11-symbols/plus.png
file=/icon/%theme_type%/9-media/paper.png
pause=/icon/%theme_type%/9-media/stop.png
start=/icon/%theme_type%/9-media/play.png
close=/icon/%theme_type%/8-ui/cross.png
edit=/icon/%theme_type%/10-editing/pencil.png
scan=/icon/%theme_type%/9-media/scan.png
login=/icon/%theme_type%/8-ui/user-avatar-02.png
choose=/icon/%theme_type%/8-ui/grid-add.png
power_switch=/icon/%theme_type%/9-media/power-switch.png
link=/icon/%theme_type%/9-media/share.png
trash=/icon/%theme_type%/9-media/trash.png
update=/icon/%theme_type%/9-media/cloud-download.png
